### ISSUE TITLE
Roadmap for next major release

### ISSUE THREAD

**Issue by JrSchild** [JrSchild/jr-crop#24]
To my knowledge this is still the most desired image cropper for Ionic. Unfortunately I am no longer actively maintaining this plugin. However to make this project future proof and if there is enough support from the community and contributors we can slowly start looking at what this library needs for a next major release. 

I am unsure how much time I have to work on this. Before I start planning anything I will require some community feedback on the following items that came up.

- [ ] Fully tested support for Android
- [ ] Extensive unit testing
- [ ] API redesign
- [ ] Internal refactor
    - [ ] Fix laggy/jumpy behavior
    - [ ] Change the way jr-crop gets instantiated
- [ ] Improve documentation and examples
    - [ ] How to send large images (.toBlob()/polyfill?) and receive/store them on the server #23
    - [ ] Known (security) issues/Troubleshooting
    - [ ] How to use the Camera/Photo Library (iOS + Android) with jr-crop
    - [ ] API options
    - [ ] ?
- [ ] Features
    - [ ] Crop surface dependent of screen size
    - [ ] Ratio options
    - [ ] Crop canvas to circle
    - [ ] Export to image file (PNG/JPG)
    - [ ] Scaling? #17
    - [ ] Support other croppable elements than a URL
    - [ ] ?
- [ ] Ionic v2 support?
- [ ] Desktop support (scale)?
- [ ] Improve extensibility?

**Comment by 0x1ad2** [comment]
Does the feature
- [ ] Ratio options

also fix the issue https://github.com/JrSchild/jr-crop/issues/28

When is the release expected and is there some way to fix the ratio problem myself?
